name: Release CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_push_server:
    name: Build and Push Server Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/corkine/frog-game:${{ github.ref_name }}
          build-args: |
            APP_VERSION=${{ github.ref_name }}

  build_cross_platform:
    name: Build Flutter App for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Linux-specific setup
      - name: Install Linux build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev zip

      # Android-specific setup (on Linux runner)
      - name: Set up Java for Android
        if: runner.os == 'Linux'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Enable desktop support
        if: runner.os != 'Linux' # Linux is enabled by default with install
        run: flutter config --enable-${{ runner.os == 'Windows' && 'windows' || 'macos' }}-desktop

      # Build Steps
      - name: Build Web
        if: runner.os == 'Linux'
        run: flutter build web --release --base-href=/frog/ --dart-define=APP_VERSION=${{ github.ref_name }} --dart-define=SERVER_URL=${{ secrets.SERVER_URL }}

      - name: Build Linux
        if: runner.os == 'Linux'
        run: flutter build linux --release --dart-define=APP_VERSION=${{ github.ref_name }} --dart-define=SERVER_URL=${{ secrets.SERVER_URL }}

      - name: Build Android APK
        if: runner.os == 'Linux'
        run: flutter build apk --release --dart-define=APP_VERSION=${{ github.ref_name }} --dart-define=SERVER_URL=${{ secrets.SERVER_URL }}

      - name: Build Windows
        if: runner.os == 'Windows'
        run: flutter build windows --release --dart-define=APP_VERSION=${{ github.ref_name }} --dart-define=SERVER_URL=${{ secrets.SERVER_URL }}

      - name: Build macOS
        if: runner.os == 'macOS'
        run: flutter build macos --release --dart-define=APP_VERSION=${{ github.ref_name }} --dart-define=SERVER_URL=${{ secrets.SERVER_URL }}

      - name: Build iOS
        if: runner.os == 'macOS'
        run: flutter build ios --release --no-codesign --dart-define=APP_VERSION=${{ github.ref_name }} --dart-define=SERVER_URL=${{ secrets.SERVER_URL }}

      # Packaging and Uploading Artifacts
      - name: Package Web build
        if: runner.os == 'Linux'
        run: zip -r web-build.zip build/web

      - name: Package Linux build
        if: runner.os == 'Linux'
        run: zip -r linux-build.zip build/linux/x64/release/bundle

      - name: Package Windows build
        if: runner.os == 'Windows'
        shell: pwsh
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath windows-build.zip
          
      - name: Package macOS build
        if: runner.os == 'macOS'
        run: ditto -c -k --sequesterRsrc --keepParent "build/macos/Build/Products/Release/frog_game.app" macos-build.zip
      
      - name: Package iOS build
        if: runner.os == 'macOS'
        run: ditto -c -k --sequesterRsrc --keepParent "build/ios/iphoneos/Runner.app" ios-build.zip
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ runner.os }}
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            web-build.zip
            linux-build.zip
            windows-build.zip
            macos-build.zip
            ios-build.zip
          if-no-files-found: ignore

  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build_and_push_server, build_cross_platform]
    permissions:
      contents: write # 需要权限来创建Release

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      
      - name: List downloaded files
        run: ls -R artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          body: "自动发布版本 ${{ github.ref_name }}"
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') || contains(github.ref, '-rc') }} 